import type { Metadata } from "next";
import { Zilla_Slab, Archivo } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import WhatsAppFloat from "@/components/WhatsAppFloat";
import "./globals.css";

const zilla = Zilla_Slab({
  subsets: ["latin"],
  weight: ["600", "700"],
  variable: "--font-zilla",
});

const archivo = Archivo({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-archivo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${zilla.variable} ${archivo.variable}`}>
      <body className="font-body antialiased">
        <Header />
        <main className="pb-14 md:pb-0">{children}</main>
        <Footer />
        <WhatsAppFloat />
      </body>
    </html>
  );
}
